USE [master]
GO

/****** Object:  Database [ConsumptionDB_Dev]    Script Date: 9/8/2026 5:06:03 PM ******/
CREATE DATABASE [ConsumptionDB_Dev]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ConsumptionBayerDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\ConsumptionBayerDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ConsumptionBayerDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\ConsumptionBayerDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ConsumptionDB_Dev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ConsumptionDB_Dev] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET ARITHABORT OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET RECOVERY FULL 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET  MULTI_USER 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ConsumptionDB_Dev] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ConsumptionDB_Dev] SET QUERY_STORE = OFF
GO

USE [ConsumptionDB_Dev]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [ConsumptionDB_Dev] SET  READ_WRITE 
GO

